### ISSUE TITLE
Tests give errors when a larger file is used

### ISSUE THREAD

**Issue by Joesalmon1985** [Joesalmon1985/PandemicBoardGame#19]
When I run

python -m unittest -v t_makeboard

If I am using the data found in safetestboard.txt everything works fine (bar one fail on testing epTBL)
# 
## FAIL: test_setup_epTBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 229, in test_setup_epTBL
    self.assertNotEqual(answerX,None,'The table for the epidemic cards has no name column.')
AssertionError: The table for the epidemic cards has no name column.

---

Ran 14 tests in 10.654s

FAILED (failures=1)

However, if I switch to the bigger data found in bigtestboard.txt, and stick this in the testboard.txt I get error messages.
# 
## ERROR: test_setup_BoardTBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 11, in test_setup_BoardTBL
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## ERROR: test_setup_idTBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 68, in test_setup_idTBL
    answer0 = answerX [0]
TypeError: 'NoneType' object has no attribute '**getitem**'
# 
## ERROR: test_setup_pdTBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 43, in test_setup_pdTBL
    answer0 = answerX [0]
TypeError: 'NoneType' object has no attribute '**getitem**'
# 
## ERROR: test_setup_player1TBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 201, in test_setup_player1TBL
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## ERROR: test_setup_player2TBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 135, in test_setup_player2TBL
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## ERROR: test_setup_player3TBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 158, in test_setup_player3TBL
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## ERROR: test_setup_player4TBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 179, in test_setup_player4TBL
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## ERROR: test_setup_shuf (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 235, in test_setup_shuf
    sg.BoardTBL ('testboard.txt')
  File "makeboard.py", line 59, in BoardTBL
    cursor.execute( tobedone )
OperationalError: no such column: ‘b’
# 
## FAIL: test_setup_epTBL (t_makeboard.T)

Traceback (most recent call last):
  File "t_makeboard.py", line 229, in test_setup_epTBL
    self.assertNotEqual(answerX,None,'The table for the epidemic cards has no name column.')
AssertionError: The table for the epidemic cards has no name column.

---

Ran 14 tests in 2.829s

FAILED (failures=1, errors=8)

Any ideas why I'm getting these problems?

**Comment by Joesalmon1985** [comment]
Fixed it. Formatting error. I'm an idiot
